import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cookies } from 'next/headers';
import { ClientCookiesProvider } from '@/util/CookiesProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'The Best Todo List',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <ClientCookiesProvider value={cookies().getAll()}>
        <body className={inter.className}>{children}</body>
      </ClientCookiesProvider>
    </html>
  )
}
